[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
grains_swap = "4cK1LWtwoiJeqFNh1AE7HGtE7a4G2Am3TqbB2oo5FEXS"

[programs.devnet]
grains_swap = "4cK1LWtwoiJeqFNh1AE7HGtE7a4G2Am3TqbB2oo5FEXS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/deonabellana/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"

[tests]
grains_swap = "tests/grains_swap.js"